services:

  artrex-back:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../code:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://artrex_user:securepassword@artrex-db:5432/artrex_db
    depends_on:
      - artrex-db

  artrex-db:
    image: postgres:13
    environment:
      POSTGRES_USER: artrex_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: artrex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: